stages:
  - production

variables:
  _version: '1.6.alpha'
  _type: 'single'
  # 部署前获取 submodule，测试无效
  #GIT_SUBMODULE_STRATEGY: normal

  # 所有服务器通用变量
  fastcgi_cache_path: /var/cache/nginx/fastcgi_cache_path
  backup_keep_days: 7
  backup_dir: /usr/share/nginx/deployer_backup
  web_rootpath: /usr/share/nginx

  # 新增项目：修改项目名，此变量用于唯一标识这个项目
  project_name: "docs_dochatbot_com"
  src_name: "docs/.vitepress/dist/"
  component_name: ""
  deploy_user: "deployer"

########################### Stage production ###########################
# 部署到正式服务器
stage_production:
  stage: production
  script:
    # 简化 ssh 登录
    - TIMESTAMP=$(date +%Y%m%d%H%M%S)
    - SSH="ssh -i ~/key_${SERVER_IP}.pem -p${SERVER_PORT} ${deploy_user}@${SERVER_IP}"
    - SSH_RSYNC="ssh -i ~/key_${SERVER_IP}.pem -p${SERVER_PORT}"

    # 添加 ssh 密钥
    - cat > ~/key_${SERVER_IP}.pem <(echo "$PRODUCTION_PRIVATE_KEY")
    - chmod 600 ~/key_${SERVER_IP}.pem

    # 部署代码
    - yarn install
    - yarn docs:build

    # 复制代码到服务器
    - ${SSH} "rm -rf ${BDIR}/_tmp_${project_name} && mkdir ${BDIR}/_tmp_${project_name}"
    - rsync -Paqz -e "${SSH_RSYNC}" --exclude=.git/ ./${src_name} ${deploy_user}@${SERVER_IP}:${BDIR}/_tmp_${project_name}/
    - ${SSH} "find ${BDIR}/_tmp_${project_name} -type d -print0 | xargs -0 -n 10 chmod 775"
    - ${SSH} "find ${BDIR}/_tmp_${project_name} -type f -print0 | xargs -0 -n 10 chmod 664"

    # 复制 rsync 排除文件列表
    # 不知道为啥，只有 ${HOME} 生效
    - cat > ~/_rsync_${project_name}.exclude <(echo "$RSYNC_EXCLUDE_LIST")
    - rsync -Paqz -e "${SSH_RSYNC}" ${HOME}/_rsync_${project_name}.exclude ${deploy_user}@${SERVER_IP}:${BDIR}/_rsync_${project_name}.exclude

    # 更新代码
    - ${SSH} "mkdir -p ${WROOT}/${SITE}/${component_name}"
    - ${SSH} "rsync -POaq --exclude-from=${BDIR}/_rsync_${project_name}.exclude ${WROOT}/${SITE}/${component_name} ${BDIR}/${project_name}_${TIMESTAMP}/"
    - ${SSH} "rsync -POaq --delete --exclude-from=${BDIR}/_rsync_${project_name}.exclude ${BDIR}/_tmp_${project_name}/ ${WROOT}/${SITE}/${component_name}"
    - echo TIMESTAMP ${TIMESTAMP}

    # 移除不用文件
    - ${SSH} "rm -rf ${BDIR}/_tmp_${project_name}"
    - rm -rf ~/key_${SERVER_IP}.pem ~/_rsync_${project_name}.exclude

  parallel:
    matrix:
      - SERVER_IP: ${PRODUCTION_SERVER}
        SERVER_PORT: 22
        WROOT: ${web_rootpath}
        BDIR: ${backup_dir}
        SITE: ${PRODUCTION_LIST}

  # https://docs.gitlab.com/ee/ci/yaml/README.html#rules
  # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  rules:
    # - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_MESSAGE =~ /^Merge branch ''(staging|hotfix_\S*)'' into ''master''/'
    - if: '$CI_COMMIT_BRANCH == "master"'
  # 仅在有标签的 runner 上执行该阶段
  tags:
    - nodejs16

